// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vdual_control_switch.cpp"
#include "Vdual_control_switch___024root.cpp"
#include "Vdual_control_switch__Trace.cpp"
#include "Vdual_control_switch___024root__Slow.cpp"
#include "Vdual_control_switch__Syms.cpp"
#include "Vdual_control_switch__Trace__Slow.cpp"
